app:
  referee-base-url: ${REFEREE_BASE_URL:http://localhost:5173/}

server:
  port: ${PORT:8080}

manager:
  api-key: ${MANAGER_API_KEY:}

spring:
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:postgrad_application_db}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:${POSTGRES_PASSWORD}}

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true